project_name: "go-gh-actions"
before:
  hooks:
    - go mod tidy
builds:
  - id: "go-gh-actions"
    binary: goghactions
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - 386
      - arm64
archives:
    - format_overrides:
        - goos: windows
          format: zip
brews:
    - github:
          owner: lgdd
          name: go-gh-actions
      folder: Formula
      homepage: https://github.com/lgdd/go-gh-actions
      description: A sample go app testing GitHub Actions & GoReleaser.
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
