project_name: "go-gh-actions"
before:
  hooks:
    - go mod tidy
builds:
  - id: "go-gh-actions"
    binary: goghactions
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - 386
      - arm64
archives:
  - format_overrides:
      - goos: windows
        format: zip
    replacements:
      amd64: 64-bit
      386: 32-bit
      darwin: macOS
nfpms:
  - description: Sample project.
    homepage: https://github.com/lgdd/go-gh-actions
    license: MIT
    formats:
      - deb
      - rpm
      - apk
    replacements:
      amd64: 64-bit
      386: 32-bit
      darwin: macOS
brews:
  - 
    tap:
      owner: lgdd
      name: homebrew-go-gh-actions
      token: "{{ .Env.GH_API_TOKEN }}"
    folder: Formula
    homepage: https://github.com/lgdd/go-gh-actions
    description: A sample go app testing GitHub Actions & GoReleaser.
    install: |
      bin.install "goghactions"
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
