project_name: "go-gh-actions"
before:
  hooks:
    - go mod tidy
builds:
  - id: "go-gh-actions"
    binary: goghactions
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - 386
      - arm64
archives:
    - replacements:
        amd64: 64-bit
        386: 32-bit
        darwin: macOS
      format_overrides:
        - goos: windows
          format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
