# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoGhActions < Formula
  desc "A sample go app testing GitHub Actions & GoReleaser."
  homepage "https://github.com/lgdd/go-gh-actions"
  version "1.2.3"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lgdd/go-gh-actions/releases/download/v1.2.3/go-gh-actions_1.2.3_darwin_amd64.tar.gz"
      sha256 "8cdb10b754f2aa95943a06a653a322447d0d2c00673dc799e011b1b1898ae298"
    end
    if Hardware::CPU.arm?
      url "https://github.com/lgdd/go-gh-actions/releases/download/v1.2.3/go-gh-actions_1.2.3_darwin_arm64.tar.gz"
      sha256 "a118aa5e14637491e7808233b8556e099c58d36c44eba8ba3e4d41f1f28294e8"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/lgdd/go-gh-actions/releases/download/v1.2.3/go-gh-actions_1.2.3_linux_amd64.tar.gz"
      sha256 "89b646ccd448d88e2f92cb0f16c4533ae73e8e29dee904bfceb4ae63081fe0e0"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lgdd/go-gh-actions/releases/download/v1.2.3/go-gh-actions_1.2.3_linux_arm64.tar.gz"
      sha256 "728dd8a4544c3954c440d27385e3dd470b0bfc96d1312aa173df514a6b2240af"
    end
  end

  def install
    bin.install "go-gh-actions"
  end
end
