# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoGhActions < Formula
  desc "A sample go app testing GitHub Actions & GoReleaser."
  homepage "https://github.com/lgdd/go-gh-actions"
  version "1.2.3"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lgdd/go-gh-actions/releases/download/v1.2.3/go-gh-actions_1.2.3_darwin_amd64.tar.gz"
      sha256 "8ec00e3a2a3a4cfcdf396565b30893f1b75e076839d78c552b41a58f901d59fc"
    end
    if Hardware::CPU.arm?
      url "https://github.com/lgdd/go-gh-actions/releases/download/v1.2.3/go-gh-actions_1.2.3_darwin_arm64.tar.gz"
      sha256 "ff54c1903d2a0efe121bd452f35ffdb71f627452b6e476777e4cd2cf5f4ac6c2"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/lgdd/go-gh-actions/releases/download/v1.2.3/go-gh-actions_1.2.3_linux_amd64.tar.gz"
      sha256 "d58978117ee703f500267c1b890037d3a0524ad0b533b294a776ae9aa9e3dbf9"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lgdd/go-gh-actions/releases/download/v1.2.3/go-gh-actions_1.2.3_linux_arm64.tar.gz"
      sha256 "4e985fe8ea27fbbb5e2b5e8ab39156b42348cbe5cb8911637e20576f968e395f"
    end
  end

  def install
    bin.install "go-gh-actions"
  end
end
