# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoGhActions < Formula
  desc "A sample go app testing GitHub Actions & GoReleaser."
  homepage "https://github.com/lgdd/go-gh-actions"
  version "1.2.3"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lgdd/go-gh-actions/releases/download/v1.2.3/go-gh-actions_1.2.3_darwin_amd64.tar.gz"
      sha256 "e40140e852749f17994653dc89bb3d4fbade8fe5161f8c32556009111e875d2a"
    end
    if Hardware::CPU.arm?
      url "https://github.com/lgdd/go-gh-actions/releases/download/v1.2.3/go-gh-actions_1.2.3_darwin_arm64.tar.gz"
      sha256 "22d0ebf9237eb7502c357c6c3fb5e8924d4f9966c6e567ecf0eb00b697d20267"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/lgdd/go-gh-actions/releases/download/v1.2.3/go-gh-actions_1.2.3_linux_amd64.tar.gz"
      sha256 "1f1c5d423359117adfbf16de7771eb1f2996be03700e208f10fb8c7b1508d75f"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lgdd/go-gh-actions/releases/download/v1.2.3/go-gh-actions_1.2.3_linux_arm64.tar.gz"
      sha256 "f376c9a3f2227b10ca1593d1558f9275a68fb5459e4869501e1d30140b4ca8e4"
    end
  end

  def install
    bin.install "go-gh-actions"
  end
end
